### ISSUE TITLE
The MD32 looks like heritage from Analog Devices Division

### ISSUE THREAD

**Issue by copslock** [cyrozap/mediatek-lte-baseband-re#6]
`/************************************************************************
 *
 * cycle_count_md32.h
 *   Platform specific functions to measure cycle counts
 *
 * This header file is not meant to be included directly.  Please
 * include <cycle_count.h> instead.
 *
 ************************************************************************/

/*
 * Copyright (c) 2009 MediaTek Inc. All Rights Reserved.
 * --------------------
 * This software is protected by copyright and the information
 * contained herein is confidential.  The software may not be
 * copied and the information contained herein may not be used or
 * disclosed except with the written permission of MediaTek Inc.
 * 
 * (c) **Copyright 2004-2008 Analog Devices, Inc.  All rights reserved.**
 *
 * $Revision: 1.2 $
 */`

[News from 2007](https://corp.mediatek.com/news-events/press-releases/mediatek-inc-to-purchase-analog-devices-cellular-radio-and-baseband-chipset-operations)

**Comment by cyrozap** [comment]
Thanks, that's an interesting find. I've skimmed the instruction set references for ADI's Blackfin, SHARC, TigerSHARC, and ADSP-21xx DSPs, but unfortunately none of those ISAs matched the MD32 instructions I've seen.

It's possible that MediaTek designed their own DSP core using some of the tools they acquired from ADI, instead of using an existing design. If that's the case, it would explain the Analog Devices copyright line in that header file (probably generated by a tool or based on some generic header file), why the chips are called MD32 (MediaTek DSP 32?), and why the ELF files generated by the MD32 compiler have their machine ID set to `0x2454` (2454 is MediaTek's TWSE ticker symbol).
