### ISSUE TITLE
It may make sense to upstream this spec into https://github.com/kaitai-io/kaitai_struct_formats/ too

### ISSUE THREAD

**Issue by KOLANICH** [cyrozap/mediatek-lte-baseband-re#7]

**Comment by cyrozap** [comment]
Thank you for the suggestion. However, I won't be making an effort to upstream any of the Kaitai Struct definitions in this repository for the following reasons:

- They're reverse-engineered, which includes a lot of guesswork, and I don't want to accidentally give anyone the impression that these formats are correct/canonical.
- They can be very context-dependent, or otherwise depend on external scripts in order to parse a file correctly.
- The formats are not standardized, and tend to be ad-hoc, so a definition that works for a file from one device may not work for the same file on a different device.

If these were standardized, independently-verifiable and testable formats, then I could be certain of their quality, and that quality could easily be confirmed by others. However, this is not the case, and I would not want to submit low-quality format descriptions to the example repo.
